<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="16">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3912" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\workaround.php" backupFilePath="" originalFileLastModifTimestamp="1519833490" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="50" mapNbLine="50" mapHigherPos="-1" mapWidth="410" mapHeight="200" mapKByteInDoc="5" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="160" startPos="177" endPos="177" selMode="0" lang="Normal Text" encoding="-1" filename="D:\webroot\BTMuseum\todo.txt" backupFilePath="" originalFileLastModifTimestamp="1519833468" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="51" mapNbLine="51" mapHigherPos="-1" mapWidth="414" mapHeight="204" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="937" xOffset="0" scrollWidth="24720" startPos="46572" endPos="46588" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_built_document.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1519808309" mapFirstVisibleDisplayLine="937" mapFirstVisibleDocLine="937" mapLastVisibleDocLine="987" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="65" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="181" xOffset="0" scrollWidth="600" startPos="6003" endPos="6003" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_built_document.css" backupFilePath="" originalFileLastModifTimestamp="1519809399" mapFirstVisibleDisplayLine="181" mapFirstVisibleDocLine="181" mapLastVisibleDocLine="232" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="5" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="2293" startPos="1663" endPos="1668" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_meta.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1520438443" mapFirstVisibleDisplayLine="20" mapFirstVisibleDocLine="20" mapLastVisibleDocLine="70" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="40" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="192" xOffset="0" scrollWidth="1232" startPos="8371" endPos="8371" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1519812372" mapFirstVisibleDisplayLine="192" mapFirstVisibleDocLine="192" mapLastVisibleDocLine="243" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="16" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="2122" startPos="789" endPos="789" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Model.php" backupFilePath="" originalFileLastModifTimestamp="1520439923" mapFirstVisibleDisplayLine="200" mapFirstVisibleDocLine="200" mapLastVisibleDocLine="250" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="229" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="10" xOffset="0" scrollWidth="1248" startPos="310" endPos="323" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_AdMeta.php" backupFilePath="" originalFileLastModifTimestamp="1519794051" mapFirstVisibleDisplayLine="10" mapFirstVisibleDocLine="10" mapLastVisibleDocLine="61" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="17" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="40" xOffset="0" scrollWidth="1312" startPos="1484" endPos="1484" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_meta_admin.js" backupFilePath="" originalFileLastModifTimestamp="1519795359" mapFirstVisibleDisplayLine="40" mapFirstVisibleDocLine="40" mapLastVisibleDocLine="91" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="35" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1560" startPos="649" endPos="658" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_document.js" backupFilePath="" originalFileLastModifTimestamp="1520510330" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="51" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="60" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="389" xOffset="0" scrollWidth="2488" startPos="12036" endPos="12036" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_dobjad.js" backupFilePath="" originalFileLastModifTimestamp="1518029007" mapFirstVisibleDisplayLine="389" mapFirstVisibleDocLine="389" mapLastVisibleDocLine="439" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="54" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="6176" startPos="4141" endPos="4141" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_volumeprint.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1519812120" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="50" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="4" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="696" startPos="945" endPos="953" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Staff_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1507098817" mapFirstVisibleDisplayLine="20" mapFirstVisibleDocLine="20" mapLastVisibleDocLine="71" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="3" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="90" xOffset="0" scrollWidth="1512" startPos="7602" endPos="7602" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Staff_Model.php" backupFilePath="" originalFileLastModifTimestamp="1520437198" mapFirstVisibleDisplayLine="90" mapFirstVisibleDocLine="90" mapLastVisibleDocLine="141" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="40" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="80" xOffset="0" scrollWidth="2224" startPos="4668" endPos="4675" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_AdStaff.php" backupFilePath="" originalFileLastModifTimestamp="1520436888" mapFirstVisibleDisplayLine="80" mapFirstVisibleDocLine="80" mapLastVisibleDocLine="130" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="9" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="295" xOffset="0" scrollWidth="2397" startPos="17139" endPos="17149" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_staff.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1520436040" mapFirstVisibleDisplayLine="295" mapFirstVisibleDocLine="295" mapLastVisibleDocLine="345" mapNbLine="50" mapHigherPos="-1" mapWidth="406" mapHeight="200" mapKByteInDoc="25" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="185" xOffset="0" scrollWidth="1440" startPos="9915" endPos="9915" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_staff_admin.js" backupFilePath="" originalFileLastModifTimestamp="1520436002" mapFirstVisibleDisplayLine="185" mapFirstVisibleDocLine="185" mapLastVisibleDocLine="236" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="25" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="23" xOffset="0" scrollWidth="1128" startPos="1458" endPos="1458" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\account_login.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1520507613" mapFirstVisibleDisplayLine="23" mapFirstVisibleDocLine="23" mapLastVisibleDocLine="74" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="2" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1744" startPos="2527" endPos="2527" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\area_admin_manual.php" backupFilePath="" originalFileLastModifTimestamp="1516346653" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="51" mapNbLine="51" mapHigherPos="-1" mapWidth="407" mapHeight="204" mapKByteInDoc="3" mapWrapIndentMode="1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
