<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="279" startPos="31" endPos="31" selMode="0" lang="Normal Text" encoding="-1" filename="D:\webroot\BTMuseum\todo.txt" backupFilePath="" originalFileLastModifTimestamp="1514708850" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="48" mapNbLine="48" mapHigherPos="-1" mapWidth="312" mapHeight="192" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="954" startPos="725" endPos="725" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\conf\server_config.php" backupFilePath="" originalFileLastModifTimestamp="1513507543" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="48" mapNbLine="48" mapHigherPos="-1" mapWidth="326" mapHeight="192" mapKByteInDoc="1" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1962" startPos="927" endPos="927" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\conf\system_config.php" backupFilePath="" originalFileLastModifTimestamp="1514269042" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="47" mapNbLine="47" mapHigherPos="-1" mapWidth="326" mapHeight="188" mapKByteInDoc="14" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="18" xOffset="0" scrollWidth="1386" startPos="1256" endPos="1256" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1514518694" mapFirstVisibleDisplayLine="18" mapFirstVisibleDocLine="18" mapLastVisibleDocLine="65" mapNbLine="47" mapHigherPos="-1" mapWidth="118" mapHeight="188" mapKByteInDoc="14" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="290" xOffset="0" scrollWidth="2387" startPos="9008" endPos="9008" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Model.php" backupFilePath="" originalFileLastModifTimestamp="1514518517" mapFirstVisibleDisplayLine="290" mapFirstVisibleDocLine="290" mapLastVisibleDocLine="337" mapNbLine="47" mapHigherPos="-1" mapWidth="305" mapHeight="188" mapKByteInDoc="156" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="155" xOffset="0" scrollWidth="2592" startPos="7174" endPos="7174" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_AdMeta.php" backupFilePath="" originalFileLastModifTimestamp="1514517374" mapFirstVisibleDisplayLine="155" mapFirstVisibleDocLine="155" mapLastVisibleDocLine="202" mapNbLine="47" mapHigherPos="-1" mapWidth="305" mapHeight="188" mapKByteInDoc="14" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="2595" startPos="14692" endPos="14692" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_meta.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1514513233" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="47" mapNbLine="47" mapHigherPos="-1" mapWidth="305" mapHeight="188" mapKByteInDoc="28" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="1479" xOffset="0" scrollWidth="1764" startPos="46398" endPos="46398" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_document.js" backupFilePath="" originalFileLastModifTimestamp="1514518033" mapFirstVisibleDisplayLine="1479" mapFirstVisibleDocLine="1479" mapLastVisibleDocLine="1526" mapNbLine="47" mapHigherPos="-1" mapWidth="303" mapHeight="188" mapKByteInDoc="49" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="577" xOffset="0" scrollWidth="27810" startPos="30399" endPos="30416" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_built_document.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1514518004" mapFirstVisibleDisplayLine="577" mapFirstVisibleDocLine="577" mapLastVisibleDocLine="624" mapNbLine="47" mapHigherPos="-1" mapWidth="305" mapHeight="188" mapKByteInDoc="57" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="59" xOffset="0" scrollWidth="1494" startPos="2245" endPos="2260" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_meta_admin.js" backupFilePath="" originalFileLastModifTimestamp="1514458018" mapFirstVisibleDisplayLine="59" mapFirstVisibleDocLine="59" mapLastVisibleDocLine="107" mapNbLine="48" mapHigherPos="-1" mapWidth="347" mapHeight="192" mapKByteInDoc="28" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="597" xOffset="0" scrollWidth="2799" startPos="18475" endPos="18485" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_dobjad.js" backupFilePath="" originalFileLastModifTimestamp="1514516817" mapFirstVisibleDisplayLine="597" mapFirstVisibleDocLine="597" mapLastVisibleDocLine="644" mapNbLine="47" mapHigherPos="-1" mapWidth="346" mapHeight="188" mapKByteInDoc="49" mapWrapIndentMode="1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="5">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3141864" startPos="0" endPos="0" selMode="0" lang="Normal Text" encoding="65001" filename="D:\AppServ\Apache24\logs\error.log" backupFilePath="" originalFileLastModifTimestamp="1514515776" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="47" mapNbLine="47" mapHigherPos="-1" mapWidth="188" mapHeight="188" mapKByteInDoc="9" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="67" xOffset="0" scrollWidth="513" startPos="1909" endPos="1916" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_ad10.css" backupFilePath="" originalFileLastModifTimestamp="1513259952" mapFirstVisibleDisplayLine="67" mapFirstVisibleDocLine="67" mapLastVisibleDocLine="114" mapNbLine="47" mapHigherPos="-1" mapWidth="16" mapHeight="188" mapKByteInDoc="7" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="1203" xOffset="0" scrollWidth="1242" startPos="27748" endPos="27748" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_built_admin.css" backupFilePath="" originalFileLastModifTimestamp="1514517784" mapFirstVisibleDisplayLine="1203" mapFirstVisibleDocLine="1203" mapLastVisibleDocLine="1250" mapNbLine="47" mapHigherPos="-1" mapWidth="203" mapHeight="188" mapKByteInDoc="28" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="972" startPos="491" endPos="495" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_built_document.css" backupFilePath="" originalFileLastModifTimestamp="1514441839" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="48" mapNbLine="48" mapHigherPos="-1" mapWidth="205" mapHeight="192" mapKByteInDoc="4" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="909" startPos="747" endPos="747" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_meta_admin.css" backupFilePath="" originalFileLastModifTimestamp="1514464535" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="48" mapNbLine="48" mapHigherPos="-1" mapWidth="277" mapHeight="192" mapKByteInDoc="11" mapWrapIndentMode="1" mapIsWrap="no">
                <Mark line="147" />
            </File>
            <File firstVisibleLine="464" xOffset="0" scrollWidth="1755" startPos="15412" endPos="15412" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\systemPaser\RCDH_P02_ProcessMetadataSource.php" backupFilePath="" originalFileLastModifTimestamp="1514481019" mapFirstVisibleDisplayLine="464" mapFirstVisibleDocLine="464" mapLastVisibleDocLine="511" mapNbLine="47" mapHigherPos="-1" mapWidth="234" mapHeight="188" mapKByteInDoc="15" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="162" xOffset="0" scrollWidth="1089" startPos="5738" endPos="5738" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\systemPaser\RCDH_P03_Elasticsearch.php" backupFilePath="" originalFileLastModifTimestamp="1514481075" mapFirstVisibleDisplayLine="162" mapFirstVisibleDocLine="162" mapLastVisibleDocLine="209" mapNbLine="47" mapHigherPos="-1" mapWidth="219" mapHeight="188" mapKByteInDoc="8" mapWrapIndentMode="1" mapIsWrap="no" />
        </subView>
    </Session>
</NotepadPlus>
