<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="18">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="3912" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\workaround.php" backupFilePath="" originalFileLastModifTimestamp="1520511832" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="50" mapNbLine="50" mapHigherPos="-1" mapWidth="410" mapHeight="200" mapKByteInDoc="5" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="160" startPos="177" endPos="177" selMode="0" lang="Normal Text" encoding="-1" filename="D:\webroot\BTMuseum\todo.txt" backupFilePath="" originalFileLastModifTimestamp="1519833468" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="51" mapNbLine="51" mapHigherPos="-1" mapWidth="414" mapHeight="204" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="1369" xOffset="0" scrollWidth="27810" startPos="69591" endPos="69608" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_built_document.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1520532526" mapFirstVisibleDisplayLine="1369" mapFirstVisibleDocLine="1369" mapLastVisibleDocLine="1411" mapNbLine="42" mapHigherPos="-1" mapWidth="236" mapHeight="168" mapKByteInDoc="70" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="797" xOffset="0" scrollWidth="2488" startPos="24173" endPos="24173" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_dobjad.js" backupFilePath="" originalFileLastModifTimestamp="1520532421" mapFirstVisibleDisplayLine="797" mapFirstVisibleDocLine="797" mapLastVisibleDocLine="839" mapNbLine="42" mapHigherPos="-1" mapWidth="238" mapHeight="168" mapKByteInDoc="55" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="2293" startPos="1663" endPos="1668" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\templates\admin_meta.html5tpl.php" backupFilePath="" originalFileLastModifTimestamp="1520438443" mapFirstVisibleDisplayLine="20" mapFirstVisibleDocLine="20" mapLastVisibleDocLine="62" mapNbLine="42" mapHigherPos="-1" mapWidth="197" mapHeight="168" mapKByteInDoc="40" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="207" xOffset="0" scrollWidth="1386" startPos="8276" endPos="8276" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1520527001" mapFirstVisibleDisplayLine="207" mapFirstVisibleDocLine="207" mapLastVisibleDocLine="249" mapNbLine="42" mapHigherPos="-1" mapWidth="197" mapHeight="168" mapKByteInDoc="16" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="2196" xOffset="0" scrollWidth="2122" startPos="75421" endPos="75689" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Meta_Model.php" backupFilePath="" originalFileLastModifTimestamp="1520439923" mapFirstVisibleDisplayLine="2196" mapFirstVisibleDocLine="2196" mapLastVisibleDocLine="2238" mapNbLine="42" mapHigherPos="-1" mapWidth="262" mapHeight="168" mapKByteInDoc="229" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="10" xOffset="0" scrollWidth="1638" startPos="310" endPos="323" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_AdMeta.php" backupFilePath="" originalFileLastModifTimestamp="1519794051" mapFirstVisibleDisplayLine="10" mapFirstVisibleDocLine="10" mapLastVisibleDocLine="52" mapNbLine="42" mapHigherPos="-1" mapWidth="269" mapHeight="168" mapKByteInDoc="17" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="684" xOffset="0" scrollWidth="1476" startPos="22417" endPos="22422" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_meta_admin.js" backupFilePath="" originalFileLastModifTimestamp="1520528181" mapFirstVisibleDisplayLine="684" mapFirstVisibleDocLine="684" mapLastVisibleDocLine="726" mapNbLine="42" mapHigherPos="-1" mapWidth="238" mapHeight="168" mapKByteInDoc="35" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="703" xOffset="0" scrollWidth="1755" startPos="23624" endPos="23624" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_built_document.js" backupFilePath="" originalFileLastModifTimestamp="1520532775" mapFirstVisibleDisplayLine="693" mapFirstVisibleDocLine="693" mapLastVisibleDocLine="735" mapNbLine="42" mapHigherPos="-1" mapWidth="238" mapHeight="168" mapKByteInDoc="62" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="50" xOffset="0" scrollWidth="981" startPos="2663" endPos="2663" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Account_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1520533170" mapFirstVisibleDisplayLine="50" mapFirstVisibleDocLine="50" mapLastVisibleDocLine="93" mapNbLine="43" mapHigherPos="-1" mapWidth="239" mapHeight="172" mapKByteInDoc="4" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="104" xOffset="0" scrollWidth="1188" startPos="4249" endPos="4275" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Account_Model.php" backupFilePath="" originalFileLastModifTimestamp="1508348074" mapFirstVisibleDisplayLine="40" mapFirstVisibleDocLine="40" mapLastVisibleDocLine="83" mapNbLine="43" mapHigherPos="-1" mapWidth="239" mapHeight="172" mapKByteInDoc="25" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Admin_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1506512108" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="67111168" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1008" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Admin_Model.php" backupFilePath="" originalFileLastModifTimestamp="1507097057" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="43" mapNbLine="43" mapHigherPos="-1" mapWidth="270" mapHeight="172" mapKByteInDoc="11" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="2808" startPos="1281" endPos="1306" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_Admin.php" backupFilePath="" originalFileLastModifTimestamp="1520534080" mapFirstVisibleDisplayLine="20" mapFirstVisibleDocLine="20" mapLastVisibleDocLine="62" mapNbLine="42" mapHigherPos="-1" mapWidth="238" mapHeight="168" mapKByteInDoc="2" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="783" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Staff_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1507098817" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="43" mapNbLine="43" mapHigherPos="-1" mapWidth="239" mapHeight="172" mapKByteInDoc="3" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="356" xOffset="0" scrollWidth="1188" startPos="13425" endPos="13425" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Staff_Model.php" backupFilePath="" originalFileLastModifTimestamp="1520535159" mapFirstVisibleDisplayLine="356" mapFirstVisibleDocLine="356" mapLastVisibleDocLine="399" mapNbLine="43" mapHigherPos="-1" mapWidth="239" mapHeight="172" mapKByteInDoc="40" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="729" startPos="702" endPos="733" selMode="0" lang="Normal Text" encoding="-1" filename="D:\webroot\BTMuseum\conf\info_cht.conf" backupFilePath="" originalFileLastModifTimestamp="1519795962" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="43" mapNbLine="43" mapHigherPos="-1" mapWidth="242" mapHeight="172" mapKByteInDoc="7" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="1602" startPos="1118" endPos="1144" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\dbsql\SQL_Account.php" backupFilePath="" originalFileLastModifTimestamp="1507096660" mapFirstVisibleDisplayLine="20" mapFirstVisibleDocLine="20" mapLastVisibleDocLine="62" mapNbLine="42" mapHigherPos="-1" mapWidth="269" mapHeight="168" mapKByteInDoc="6" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="648" startPos="575" endPos="579" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Field_Controller.php" backupFilePath="" originalFileLastModifTimestamp="1516345301" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="44" mapNbLine="44" mapHigherPos="-1" mapWidth="284" mapHeight="176" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="65" xOffset="0" scrollWidth="2124" startPos="2733" endPos="2733" selMode="0" lang="PHP" encoding="-1" filename="D:\webroot\BTMuseum\mvc\main\Field_Model.php" backupFilePath="" originalFileLastModifTimestamp="1520538293" mapFirstVisibleDisplayLine="65" mapFirstVisibleDocLine="65" mapLastVisibleDocLine="107" mapNbLine="42" mapHigherPos="-1" mapWidth="269" mapHeight="168" mapKByteInDoc="4" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="981" startPos="1089" endPos="1089" selMode="0" lang="JavaScript" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\js_field_admin.js" backupFilePath="" originalFileLastModifTimestamp="1520537872" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="44" mapNbLine="44" mapHigherPos="-1" mapWidth="281" mapHeight="176" mapKByteInDoc="1" mapWrapIndentMode="1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="263" xOffset="0" scrollWidth="837" startPos="7217" endPos="7225" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_built_document.css" backupFilePath="" originalFileLastModifTimestamp="1520531819" mapFirstVisibleDisplayLine="240" mapFirstVisibleDocLine="240" mapLastVisibleDocLine="284" mapNbLine="44" mapHigherPos="-1" mapWidth="49" mapHeight="176" mapKByteInDoc="6" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="1282" xOffset="0" scrollWidth="1242" startPos="0" endPos="0" selMode="0" lang="CSS" encoding="-1" filename="D:\webroot\BTMuseum\webroot-admin\theme\css\css_built_admin.css" backupFilePath="" originalFileLastModifTimestamp="1518027054" mapFirstVisibleDisplayLine="1282" mapFirstVisibleDocLine="1282" mapLastVisibleDocLine="1326" mapNbLine="44" mapHigherPos="-1" mapWidth="176" mapHeight="176" mapKByteInDoc="29" mapWrapIndentMode="1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="595" scrollWidth="2646" startPos="0" endPos="0" selMode="0" lang="Normal Text" encoding="65001" filename="D:\AppServ\Apache24\logs\error.log" backupFilePath="" originalFileLastModifTimestamp="1520527583" mapFirstVisibleDisplayLine="0" mapFirstVisibleDocLine="0" mapLastVisibleDocLine="44" mapNbLine="44" mapHigherPos="-1" mapWidth="91" mapHeight="176" mapKByteInDoc="0" mapWrapIndentMode="1" mapIsWrap="no" />
        </subView>
    </Session>
</NotepadPlus>
